name       : perl-list-allutils
version    : 0.12
release    : 6
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/List-AllUtils-0.12.tar.gz : 0b5352317652c22b53bee64e1984efd9f21edfad321b0e5a98cdec5ec87bbcae
license    : Artistic-2.0
component  : programming.perl
summary    : Combines ListUtil, ListSomeUtils and ListUtilsBy in one bite-sized package
description: |
    Combines ListUtil, ListSomeUtils and ListUtilsBy in one bite-sized package
rundeps    :
    - perl-list-someutils
    - perl-list-utilsby
    - perl-scalar-list-utils
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
