name       : perl-list-allutils
version    : '0.16'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/List-AllUtils-0.16.tar.gz : 559b3aa911c73003a3a1ebd860d3b16e171137de8203d86be63a2390364c63dd
license    : Artistic-2.0
component  : programming.perl
summary    : Combines ListUtil, ListSomeUtils and ListUtilsBy in one bite-sized package
description: |
    Combines ListUtil, ListSomeUtils and ListUtilsBy in one bite-sized package
rundeps    :
    - perl-list-someutils
    - perl-list-utilsby
    - perl-scalar-list-utils
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
