name       : perl-list-allutils
version    : '0.19'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/List-AllUtils-0.19.tar.gz : 30a8146ab21a7787b8c56d5829cf9a7f2b15276d3b3fca07336ac38d3002ffbc
homepage   : https://metacpan.org/pod/List::AllUtils
license    : Artistic-2.0
component  : programming.perl
summary    : List::AllUtils - Combines List::Util, List::SomeUtils and List::UtilsBy in one bite-sized package
description: |
    Are you sick of trying to remember whether a particular helper is defined in List::Util, List::SomeUtils or List::UtilsBy? I sure am. Now you don't have to remember. This module will export all of the functions that either of those three modules defines.
rundeps    :
    - perl-list-someutils
    - perl-list-utilsby
    - perl-scalar-list-utils
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
